package(default_visibility = ["//visibility:public"])

cc_library(
	name = "key",
	srcs = [
		"key.cpp"
	],
	hdrs = [
		"key.hpp"
	],
)

cc_library(
	name = "matrix",
	srcs = [
		"matrix.cpp"
	],
	hdrs = [
		"matrix.hpp"
	]
)
