cc_test(
    name = "matrix",
    srcs = [
        "matrix.cpp"
    ],
    deps = [
        "@gtest//:gtest_main",
        "//lib/math:matrix",
        "//lib/aes-128:defines"
    ],
)

cc_test(
    name = "algebra",
    srcs = [
        "algebra.cpp"
    ],
    deps = [
        "@gtest//:gtest_main",
        "//lib/math:algebra",
    ],
)
