cc_test(
    name = "aes_128",
    srcs = [
        "aes_128.cpp"
    ],
    deps = [
        "@gtest//:gtest_main",
        "//lib/aes-128:aes_128",
        "//lib/math:matrix",
        "//lib/math:random",
    ],
)
