on: push
name: My Action
jobs:
  checks:
    name: Testing Cryptography Project
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Mount bazel cache
      uses: actions/cache@v1
      with:
        path: "/home/runner/.cache/bazel"
        key: bazel

    - name: Install bazelisk
      run: |
        curl -LO "https://github.com/bazelbuild/bazelisk/releases/download/v1.1.0/bazelisk-linux-amd64"
        mkdir -p "${GITHUB_WORKSPACE}/bin/"
        mv bazelisk-linux-amd64 "${GITHUB_WORKSPACE}/bin/bazel"
        chmod +x "${GITHUB_WORKSPACE}/bin/bazel"

    - name: Installing GMP Library
      run: |
        sudo apt-get install -y libgmp-dev

    - name: Test Library
      run: |
        "${GITHUB_WORKSPACE}/bin/bazel" test --test_output=all //lib/...
